### PR TITLE
Add support to all Laravel 7.x versions

### PR DESCRIPTION
**Pull request by beingjungshahi**
Support all laravel 7.x versions

### CODE REVIEW

**Comment by igaster** [comment]
Hello @beingjungshahi,

Current implementation should support all 7.x versions. It evaluates to `>=7.0.0 <8.0.0`

ie latest laravel version 7.1 is supported: https://jubianchi.github.io/semver-check/#/^7.0/7.1.0

What is your framework version? Did the proposed change solved your issue?

**Comment by vesper8** [comment]
@igaster I can confirm your package does not install on a fresh installation of Laravel 7:

```
Using version ^1.3 for igaster/laravel_cities
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install igaster/laravel_cities v1.3.8
    - Conclusion: don't install igaster/laravel_cities v1.3.7
    - Conclusion: don't install igaster/laravel_cities v1.3.6
    - Conclusion: don't install igaster/laravel_cities v1.3.5
    - Conclusion: don't install igaster/laravel_cities v1.3.4
    - Conclusion: don't install igaster/laravel_cities v1.3.3
    - Conclusion: don't install igaster/laravel_cities v1.3.2
    - Conclusion: don't install igaster/laravel_cities v1.3.1
    - Conclusion: remove laravel/framework v7.4.0
    - Installation request for igaster/laravel_cities ^1.3 -> satisfiable by igaster/laravel_cities[v1.3, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8].
    - Conclusion: don't install laravel/framework v7.4.0
    - igaster/laravel_cities v1.3 requires illuminate/contracts 5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by illuminate/contracts[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/contracts 5.1.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts 5.2.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts 5.3.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts 5.4.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.1|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.13|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.16|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.20|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.22|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.25|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.28|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.30|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.31|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.41|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.1.8|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.0|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.19|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.21|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.24|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.25|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.26|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.27|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.28|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.31|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.32|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.37|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.43|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.45|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.6|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.2.7|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.3.0|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.3.16|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.3.23|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.3.4|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.0|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.13|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.17|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.19|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.27|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.36|don't install laravel/framework v7.4.0
    - don't install illuminate/contracts v5.4.9|don't install laravel/framework v7.4.0
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by beingjungshahi** [comment]
@igaster I tried to upgrade my laravel 6 app to version 7 and the error occurred. It was fixed in this commit.

**Comment by igaster** [comment]
Thanks for the feedback... I've released the package version

**Pull request merged**
